### PR TITLE
Refactor all mentions of TAD to AMT

### PR DESCRIPTION
**Pull request by laurensWe**
# Description

Renamed all mentions of TAD to AMT 
TODO: rename the links (in the ai-validation)
TODO: rename the github project (then everybody update your origin locally)

Resolves #

## Checklist

Please check all the boxes that apply to this pull request using "x":

- [x]  I have tested the changes locally and verified that they work as expected.
- [x]  I have followed the project's coding conventions and style guidelines.
- [x]  I have rebased my branch onto the latest commit of the main branch.
- [x]  I have squashed or reorganized my commits into logical units.
- [x]  I have read, understood and agree to the [Developer Certificate of Origin](../blob/main/DCO.md), which this project utilizes.

### CODE REVIEW

**Comment by laurensWe** [comment]
The CI pipelines fails because I assume that we also will rename the repository and therefore the github image is still incorrect but also the sonar cloud integration

**Comment by berrydenhartog** [comment]
I think you also need to regenerate the translations

**Review by berrydenhartog — DISMISSED** [review]
LGTM

**Review by berrydenhartog — APPROVED** [review]
LGTM

**Pull request merged**
